import { TranslateLoader } from '@ngx-translate/core';
import { Observable, of } from 'rxjs';

const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    'page.firstWeighment': 'First Weighment',
    'page.secondWeighment': 'Second Weighment',
    'page.directComplete': 'Direct Complete',
    'page.oneGoWeighment': 'One-Go Weighment',
    'page.printDuplicate': 'Print Duplicate',

    'lbl.weightType': 'Weight Type',
    'lbl.vehicleNumber': 'Vehicle Number',
    'lbl.vehicleType': 'Vehicle Type',
    'lbl.charges': 'Charges (₹)',
    'lbl.paymentMode': 'Payment Mode',
    'lbl.amountPaid': 'Amount Paid (₹)',
    'lbl.material': 'Material',
    'lbl.client': 'Client',
    'lbl.driverName': 'Driver Name',
    'lbl.confirmSave': 'Confirm & Save',
    'lbl.confirmComplete': 'Confirm & Complete',
    'lbl.secondWeight': 'Second Weight (kg)',
    'lbl.grossWeight': 'Gross Weight (kg)',
    'lbl.tareWeight': 'Known Tare Weight (kg)',
    'lbl.ticketNumber': 'Ticket Number',
    'lbl.ticketDetailsPrint': 'Ticket Details & Print',
    'lbl.liveScale': 'Live Scale',
    'lbl.captureOptions': 'Capture Options',
    'lbl.vehicleImage': 'Vehicle Image',
    'lbl.operatorImage': 'Operator Image',
    'lbl.requestPrint': 'Request Print',
    'lbl.optional': '(optional)',
    'lbl.pendingTickets': 'Pending Tickets',

    'btn.gross': 'Gross',
    'btn.tare': 'Tare',
    'btn.cash': 'Cash',
    'btn.online': 'Online',
    'btn.credit': 'Credit',
    'btn.completeWeighment': 'Complete Weighment',
    'btn.confirmSave': 'Confirm & Save',
    'btn.newEntry': 'New Entry',
    'btn.newTicket': 'New Ticket',
    'btn.printTicket': 'Print Ticket',
    'btn.printAnother': 'Print Another Copy',
    'btn.printDuplicate': 'Print Duplicate',
    'btn.newSearch': 'New Search',
    'btn.backToList': 'Back to List',
    'btn.newWeighment': 'New Weighment',

    'tbl.ticket': 'Ticket',
    'tbl.vehicle': 'Vehicle',
    'tbl.client': 'Client',
    'tbl.driver': 'Driver',
    'tbl.firstWeight': '1st Weight (kg)',
    'tbl.firstTime': '1st Time',
    'tbl.charges': 'Charges',

    'print.ticketSaved': 'Ticket Saved',
    'print.weighmentComplete': 'Weighment Complete',
    'print.vehicle': 'Vehicle',
    'print.weightType': 'Weight Type',
    'print.weight': 'Weight',
    'print.firstWeight': '1st Weight',
    'print.secondWeight': '2nd Weight',
    'print.grossWeight': 'Gross Weight',
    'print.tareWeight': 'Tare Weight',
    'print.netWeight': 'Net Weight',
    'print.material': 'Material',
    'print.client': 'Client',
    'print.driver': 'Driver',
    'print.charges': 'Charges',
    'print.paid': 'Paid',
    'print.payment': 'Payment',
    'print.suggestedCharges': 'Suggested ₹',
    'print.printing': 'Printing…',
    'print.ticketNum': 'Ticket #',
    'print.serialNum': 'Serial #',
    'print.status': 'Status',
    'print.amountPaid': 'Amount Paid',
    'print.paymentMode': 'Payment Mode',
    'print.paymentStatus': 'Payment Status',
    'print.createdBy': 'Created By',
    'print.createdAt': 'Created At',

    'status.completed': 'Completed',
    'status.pendingSecond': 'Pending 2nd Weight',
    'status.cancelled': 'Cancelled',

    'msg.noPending': 'No pending tickets found',
    'msg.noMatch': 'No tickets match your search',

    'dash.title': 'Dashboard',
    'dash.newWeighment': 'New Weighment',
    'dash.newWeighmentDesc': 'First weighment entry',
    'dash.directComplete': 'Direct Complete',
    'dash.directCompleteDesc': 'Complete by ticket number',
    'dash.oneGo': 'One-Go',
    'dash.oneGoDesc': 'Gross + known tare in one shot',
    'dash.ticketList': 'Ticket List',
    'dash.ticketListDesc': 'Complete pending tickets',
    'dash.reports': 'Reports',
    'dash.reportsDesc': 'View weighment reports',
    'dash.keyboardShortcuts': 'Keyboard Shortcuts',
    'dash.shortcutNewWeighment': 'New Weighment',
    'dash.shortcutDirectComplete': 'Direct Complete',
    'dash.shortcutTicketList': 'Ticket List',
    'dash.shortcutOneGo': 'One-Go Weighment',
    'dash.shortcutDashboard': 'Go to Dashboard',
    'dash.shortcutNavigate': 'Navigate / step form',
    'dash.shortcutSelect': 'Select / save form',
    'dash.shortcutPrint': 'Print (where applicable)',
    'dash.liveScale': 'Live Scale',
    'dash.connected': 'CONNECTED',
    'dash.reconnecting': 'RECONNECT...',
    'dash.offline': 'OFFLINE',
    'dash.stable': 'STABLE',
    'dash.motion': 'MOTION',
    'dash.quickActions': 'Quick Actions',
    'dash.zeroScale': 'Zero Scale',
  },

  hi: {
    'page.firstWeighment': 'प्रथम तुलाई',
    'page.secondWeighment': 'द्वितीय तुलाई',
    'page.directComplete': 'डायरेक्ट पूर्ण',
    'page.oneGoWeighment': 'एकल तुलाई',
    'page.printDuplicate': 'डुप्लीकेट प्रिंट',

    'lbl.weightType': 'वज़न प्रकार',
    'lbl.vehicleNumber': 'वाहन संख्या',
    'lbl.vehicleType': 'वाहन प्रकार',
    'lbl.charges': 'शुल्क (₹)',
    'lbl.paymentMode': 'भुगतान विधि',
    'lbl.amountPaid': 'भुगतान राशि (₹)',
    'lbl.material': 'सामग्री',
    'lbl.client': 'ग्राहक',
    'lbl.driverName': 'चालक का नाम',
    'lbl.confirmSave': 'पुष्टि करें और सहेजें',
    'lbl.confirmComplete': 'पुष्टि करें और पूर्ण करें',
    'lbl.secondWeight': 'द्वितीय वज़न (कि.ग्रा.)',
    'lbl.grossWeight': 'कुल वज़न (कि.ग्रा.)',
    'lbl.tareWeight': 'ज्ञात टेर वज़न (कि.ग्रा.)',
    'lbl.ticketNumber': 'टिकट संख्या',
    'lbl.ticketDetailsPrint': 'टिकट विवरण और प्रिंट',
    'lbl.liveScale': 'लाइव तराजू',
    'lbl.captureOptions': 'कैप्चर विकल्प',
    'lbl.vehicleImage': 'वाहन छवि',
    'lbl.operatorImage': 'ऑपरेटर छवि',
    'lbl.requestPrint': 'प्रिंट अनुरोध',
    'lbl.optional': '(वैकल्पिक)',
    'lbl.pendingTickets': 'लंबित टिकट',

    'btn.gross': 'कुल',
    'btn.tare': 'टेर',
    'btn.cash': 'नकद',
    'btn.online': 'ऑनलाइन',
    'btn.credit': 'उधार',
    'btn.completeWeighment': 'तुलाई पूर्ण करें',
    'btn.confirmSave': 'पुष्टि करें और सहेजें',
    'btn.newEntry': 'नई प्रविष्टि',
    'btn.newTicket': 'नया टिकट',
    'btn.printTicket': 'टिकट प्रिंट करें',
    'btn.printAnother': 'और एक प्रति प्रिंट करें',
    'btn.printDuplicate': 'डुप्लीकेट प्रिंट',
    'btn.newSearch': 'नई खोज',
    'btn.backToList': 'सूची पर वापस',
    'btn.newWeighment': 'नई तुलाई',

    'tbl.ticket': 'टिकट',
    'tbl.vehicle': 'वाहन',
    'tbl.client': 'ग्राहक',
    'tbl.driver': 'चालक',
    'tbl.firstWeight': 'प्रथम वज़न (कि.ग्रा.)',
    'tbl.firstTime': 'प्रथम समय',
    'tbl.charges': 'शुल्क',

    'print.ticketSaved': 'टिकट सहेजा',
    'print.weighmentComplete': 'तुलाई पूर्ण',
    'print.vehicle': 'वाहन',
    'print.weightType': 'वज़न प्रकार',
    'print.weight': 'वज़न',
    'print.firstWeight': 'प्रथम वज़न',
    'print.secondWeight': 'द्वितीय वज़न',
    'print.grossWeight': 'कुल वज़न',
    'print.tareWeight': 'टेर वज़न',
    'print.netWeight': 'शुद्ध वज़न',
    'print.material': 'सामग्री',
    'print.client': 'ग्राहक',
    'print.driver': 'चालक',
    'print.charges': 'शुल्क',
    'print.paid': 'भुगतान',
    'print.payment': 'भुगतान स्थिति',
    'print.suggestedCharges': 'सुझावित ₹',
    'print.printing': 'प्रिंट हो रहा है…',
    'print.ticketNum': 'टिकट #',
    'print.serialNum': 'क्रम #',
    'print.status': 'स्थिति',
    'print.amountPaid': 'भुगतान राशि',
    'print.paymentMode': 'भुगतान विधि',
    'print.paymentStatus': 'भुगतान स्थिति',
    'print.createdBy': 'द्वारा बनाया',
    'print.createdAt': 'बनाया गया',

    'status.completed': 'पूर्ण',
    'status.pendingSecond': 'द्वितीय तुलाई बाकी',
    'status.cancelled': 'रद्द',

    'msg.noPending': 'कोई लंबित टिकट नहीं',
    'msg.noMatch': 'खोज से कोई टिकट नहीं मिला',

    'dash.title': 'डैशबोर्ड',
    'dash.newWeighment': 'नई तुलाई',
    'dash.newWeighmentDesc': 'प्रथम तुलाई प्रविष्टि',
    'dash.directComplete': 'डायरेक्ट पूर्ण',
    'dash.directCompleteDesc': 'टिकट नंबर से पूर्ण',
    'dash.oneGo': 'एक-गो',
    'dash.oneGoDesc': 'एक बार में कुल + टेर',
    'dash.ticketList': 'टिकट सूची',
    'dash.ticketListDesc': 'लंबित टिकट पूर्ण करें',
    'dash.reports': 'रिपोर्ट',
    'dash.reportsDesc': 'तुलाई रिपोर्ट देखें',
    'dash.keyboardShortcuts': 'कीबोर्ड शॉर्टकट',
    'dash.shortcutNewWeighment': 'नई तुलाई',
    'dash.shortcutDirectComplete': 'डायरेक्ट पूर्ण',
    'dash.shortcutTicketList': 'टिकट सूची',
    'dash.shortcutOneGo': 'एक-गो तुलाई',
    'dash.shortcutDashboard': 'डैशबोर्ड पर जाएं',
    'dash.shortcutNavigate': 'नेविगेट / फॉर्म स्टेप',
    'dash.shortcutSelect': 'चुनें / फॉर्म सहेजें',
    'dash.shortcutPrint': 'प्रिंट (जहाँ लागू हो)',
    'dash.liveScale': 'लाइव तराजू',
    'dash.connected': 'कनेक्टेड',
    'dash.reconnecting': 'पुनः जोड़ रहा...',
    'dash.offline': 'ऑफ़लाइन',
    'dash.stable': 'स्थिर',
    'dash.motion': 'गतिमान',
    'dash.quickActions': 'त्वरित क्रियाएं',
    'dash.zeroScale': 'स्केल ज़ीरो करें',
  },

  gu: {
    'page.firstWeighment': 'પ્રથમ તોળ',
    'page.secondWeighment': 'બીજો તોળ',
    'page.directComplete': 'ડાઇરેક્ટ પૂર્ણ',
    'page.oneGoWeighment': 'એક-ગો તોળ',
    'page.printDuplicate': 'ડુપ્લિકેટ પ્રિન્ટ',

    'lbl.weightType': 'વજન પ્રકાર',
    'lbl.vehicleNumber': 'વાહન નંબર',
    'lbl.vehicleType': 'વાહન પ્રકાર',
    'lbl.charges': 'ચાર્જ (₹)',
    'lbl.paymentMode': 'ચુકવણી પ્રકાર',
    'lbl.amountPaid': 'ચૂકવેલ રકમ (₹)',
    'lbl.material': 'સામગ્રી',
    'lbl.client': 'ગ્રાહક',
    'lbl.driverName': 'ડ્રાઇવરનું નામ',
    'lbl.confirmSave': 'પુષ્ટિ કરો અને સાચવો',
    'lbl.confirmComplete': 'પુષ્ટિ કરો અને પૂર્ણ કરો',
    'lbl.secondWeight': 'બીજો વજન (કિ.ગ્રા.)',
    'lbl.grossWeight': 'કુલ વજન (કિ.ગ્રા.)',
    'lbl.tareWeight': 'ટેર વજન (કિ.ગ્રા.)',
    'lbl.ticketNumber': 'ટિકિટ નંબર',
    'lbl.ticketDetailsPrint': 'ટિકિટ વિગત અને પ્રિન્ટ',
    'lbl.liveScale': 'લાઇવ ત્રાજવું',
    'lbl.captureOptions': 'કેપ્ચર વિકલ્પો',
    'lbl.vehicleImage': 'વાહન ફોટો',
    'lbl.operatorImage': 'ઓપરેટર ફોટો',
    'lbl.requestPrint': 'પ્રિન્ટ વિનંતી',
    'lbl.optional': '(વૈકલ્પિક)',
    'lbl.pendingTickets': 'પ્રતીક્ષિત ટિકિટ',

    'btn.gross': 'કુલ',
    'btn.tare': 'ટેર',
    'btn.cash': 'રોકડ',
    'btn.online': 'ઓનલાઇન',
    'btn.credit': 'ઉધાર',
    'btn.completeWeighment': 'તોળ પૂર્ણ કરો',
    'btn.confirmSave': 'પુષ્ટિ કરો અને સાચવો',
    'btn.newEntry': 'નવી એન્ટ્રી',
    'btn.newTicket': 'નવી ટિકિટ',
    'btn.printTicket': 'ટિકિટ પ્રિન્ટ',
    'btn.printAnother': 'બીજી નકલ પ્રિન્ટ',
    'btn.printDuplicate': 'ડુપ્લિકેટ પ્રિન્ટ',
    'btn.newSearch': 'નવી શોધ',
    'btn.backToList': 'સૂચિ પર પાછા',
    'btn.newWeighment': 'નવો તોળ',

    'tbl.ticket': 'ટિકિટ',
    'tbl.vehicle': 'વાહન',
    'tbl.client': 'ગ્રાહક',
    'tbl.driver': 'ડ્રાઇવર',
    'tbl.firstWeight': 'પ્રથમ વજન (કિ.ગ્રા.)',
    'tbl.firstTime': 'પ્રથમ સમય',
    'tbl.charges': 'ચાર્જ',

    'print.ticketSaved': 'ટિકિટ સાચવ્યો',
    'print.weighmentComplete': 'તોળ પૂર્ણ',
    'print.vehicle': 'વાહન',
    'print.weightType': 'વજન પ્રકાર',
    'print.weight': 'વજન',
    'print.firstWeight': 'પ્રથમ વજન',
    'print.secondWeight': 'બીજો વજન',
    'print.grossWeight': 'કુલ વજન',
    'print.tareWeight': 'ટેર વજન',
    'print.netWeight': 'ચોખ્ખો વજન',
    'print.material': 'સામગ્રી',
    'print.client': 'ગ્રાહક',
    'print.driver': 'ડ્રાઇવર',
    'print.charges': 'ચાર્જ',
    'print.paid': 'ચૂકવ્યું',
    'print.payment': 'ચુકવણી સ્થિતિ',
    'print.suggestedCharges': 'સૂચિત ₹',
    'print.printing': 'પ્રિન્ટ થઇ રહ્યું…',
    'print.ticketNum': 'ટિકિટ #',
    'print.serialNum': 'ક્રમ #',
    'print.status': 'સ્થિતિ',
    'print.amountPaid': 'ચૂકવેલ રકમ',
    'print.paymentMode': 'ચુકવણી પ્રકાર',
    'print.paymentStatus': 'ચુકવણી સ્થિતિ',
    'print.createdBy': 'બનાવ્યું',
    'print.createdAt': 'બનાવ્યો સમય',

    'status.completed': 'પૂર્ણ',
    'status.pendingSecond': 'બીજો તોળ બાકી',
    'status.cancelled': 'રદ',

    'msg.noPending': 'કોઈ પ્રતીક્ષિત ટિકિટ નથી',
    'msg.noMatch': 'શોધ સાથે કોઈ ટિકિટ નથી',

    'dash.title': 'ડૅશબોર્ડ',
    'dash.newWeighment': 'નવો તોળ',
    'dash.newWeighmentDesc': 'પ્રથમ તોળ નોંધ',
    'dash.directComplete': 'ડાઇરેક્ટ પૂર્ણ',
    'dash.directCompleteDesc': 'ટિકિટ નંબરથી પૂર્ણ',
    'dash.oneGo': 'એક-ગો',
    'dash.oneGoDesc': 'એકસાથે કુલ + ટેર',
    'dash.ticketList': 'ટિકિટ સૂચિ',
    'dash.ticketListDesc': 'પ્રતીક્ષિત ટિકિટ પૂર્ણ કરો',
    'dash.reports': 'અહેવાલ',
    'dash.reportsDesc': 'તોળ અહેવાલ જુઓ',
    'dash.keyboardShortcuts': 'કીબોર્ડ શૉર્ટકટ',
    'dash.shortcutNewWeighment': 'નવો તોળ',
    'dash.shortcutDirectComplete': 'ડાઇરેક્ટ પૂર્ણ',
    'dash.shortcutTicketList': 'ટિકિટ સૂચિ',
    'dash.shortcutOneGo': 'એક-ગો તોળ',
    'dash.shortcutDashboard': 'ડૅશબોર્ડ પર જાઓ',
    'dash.shortcutNavigate': 'નેવિગેટ / ફૉર્મ સ્ટેપ',
    'dash.shortcutSelect': 'પસંદ / ફૉર્મ સાચવો',
    'dash.shortcutPrint': 'પ્રિન્ટ (જ્યાં લાગુ)',
    'dash.liveScale': 'લાઇવ ત્રાજવું',
    'dash.connected': 'કનેક્ટેડ',
    'dash.reconnecting': 'ફરી જોડાઇ રહ્યું...',
    'dash.offline': 'ઑફ઼લાઇન',
    'dash.stable': 'સ્થિર',
    'dash.motion': 'ગતિમાન',
    'dash.quickActions': 'ઝડપી ક્રિયાઓ',
    'dash.zeroScale': 'સ્કેલ ઝીરો કરો',
  },
};

export class InlineTranslateLoader implements TranslateLoader {
  getTranslation(lang: string): Observable<Record<string, string>> {
    return of(TRANSLATIONS[lang] ?? TRANSLATIONS['en']);
  }
}
